function model = build_sampling_model()
% Rebuild the closed-loop model from the supplied continuous motor blocks.
folder = fileparts(mfilename('fullpath'));
model = 'basebot_model_sampling';
target = fullfile(folder, [model '.slx']);
if bdIsLoaded(model)
    error('Close basebot_model_sampling before rebuilding to protect unsaved edits.');
end
source = 'motor_model_23b';
sourceWasLoaded = bdIsLoaded(source);
load_system(fullfile(folder, [source '.slx']));
new_system(model);
mw = get_param(model, 'ModelWorkspace');
defaults = struct('L',1e-3,'R',1,'Kt',0.01,'Kb',0.01,'J',1e-5,...
    'D',1e-5,'gear',9.68,'wheelRadius',0.03,'Kp',0.05,'Ts',0.001,...
    'referenceSpeed',0.1,'stepTime',0.2);
names = fieldnames(defaults);
for k = 1:numel(names)
    assignin(mw, names{k}, defaults.(names{k}));
end
set_param(model, 'SolverType','Variable-step','Solver','ode45',...
    'RelTol','1e-6','AbsTol','1e-9','MaxStep','min(Ts/10,0.001)',...
    'StopTime','0.6','ReturnWorkspaceOutputs','on');

plant = [model '/Motor'];
add_block('built-in/Subsystem', plant, 'Position',[650 135 760 205]);
% Copy the original blocks and internal connections, without its input source,
% kinematics or logging. The integrators retain the original initial states.
blocks = {'Sum1','Sum','Gain','Integrator','Gain1','Sum2','Gain2',...
    'Integrator1','Gain3','Gain4','Gain5'};
for k = 1:numel(blocks)
    add_block([source '/' blocks{k}], [plant '/' blocks{k}]);
end
add_block('simulink/Ports & Subsystems/In1',[plant '/Voltage'],'Position',[350 260 380 280]);
add_block('simulink/Ports & Subsystems/Out1',[plant '/Omega'],'Position',[850 260 880 280],'Port','1');
add_block('simulink/Ports & Subsystems/Out1',[plant '/Current'],'Position',[630 190 660 210],'Port','2');
connections = {'Voltage/1','Sum1/1';'Sum1/1','Sum/1';'Sum/1','Gain/1';...
    'Gain/1','Integrator/1';'Integrator/1','Gain1/1';'Integrator/1','Gain4/1';...
    'Integrator/1','Current/1';'Gain4/1','Sum/2';'Gain1/1','Sum2/1';...
    'Sum2/1','Gain2/1';'Gain2/1','Integrator1/1';'Integrator1/1','Omega/1';...
    'Integrator1/1','Gain3/1';'Integrator1/1','Gain5/1';...
    'Gain3/1','Sum2/2';'Gain5/1','Sum1/2'};
for k = 1:size(connections,1)
    add_line(plant,connections{k,1},connections{k,2},'autorouting','on');
end

add_block('simulink/Sources/Step',[model '/Reference'], 'Position',[40 140 70 170],...
    'Time','stepTime','Before','0','After','referenceSpeed','SampleTime','0');
add_block('simulink/Math Operations/Gain',[model '/Input kinematics'],...
    'Position',[120 135 205 175],'Gain','gear/wheelRadius');
add_block('simulink/Math Operations/Sum',[model '/Error'],...
    'Position',[260 140 285 165],'Inputs','+-');
add_block('simulink/Math Operations/Gain',[model '/P controller'],...
    'Position',[330 135 390 175],'Gain','Kp');
add_block('simulink/Discontinuities/Saturation',[model '/Voltage limit'],...
    'Position',[435 135 485 175],'UpperLimit','9','LowerLimit','-9');
add_block('simulink/Discrete/Zero-Order Hold',[model '/DA hold'],...
    'Position',[540 135 590 175],'SampleTime','Ts');
add_block('simulink/Continuous/Transport Delay',[model '/detect_delay'],...
    'Position',[520 280 590 320],'DelayTime','Ts','InitialOutput','0');
add_block('simulink/Discrete/Zero-Order Hold',[model '/AD hold'],...
    'Position',[350 280 410 320],'SampleTime','Ts');
add_block('simulink/Math Operations/Gain',[model '/Gear conversion'],...
    'Position',[810 135 870 175],'Gain','1/gear');
add_block('simulink/Math Operations/Gain',[model '/Wheel conversion'],...
    'Position',[920 135 990 175],'Gain','wheelRadius');
add_block('simulink/Math Operations/Gain',[model '/Voltage plot scale'],...
    'Position',[650 40 720 80],'Gain','0.1');
add_block('simulink/Signal Routing/Mux',[model '/Plot signals'],...
    'Position',[1060 40 1065 120],'Inputs','3');
add_block('simulink/Sinks/To Workspace',[model '/velP'],...
    'Position',[1110 60 1190 95],'VariableName','velP',...
    'SaveFormat','Timeseries','MaxDataPoints','inf');
add_block('simulink/Sinks/Scope',[model '/Response'], 'Position',[1110 140 1150 175]);
connections = {'Reference/1','Input kinematics/1';'Input kinematics/1','Error/1';...
    'Error/1','P controller/1';'P controller/1','Voltage limit/1';...
    'Voltage limit/1','DA hold/1';'DA hold/1','Motor/1';...
    'Motor/1','detect_delay/1';'detect_delay/1','AD hold/1';'AD hold/1','Error/2';...
    'Motor/1','Gear conversion/1';'Gear conversion/1','Wheel conversion/1';...
    'DA hold/1','Voltage plot scale/1';'Reference/1','Plot signals/1';...
    'Voltage plot scale/1','Plot signals/2';'Wheel conversion/1','Plot signals/3';...
    'Plot signals/1','velP/1';'Plot signals/1','Response/1'};
for k = 1:size(connections,1)
    add_line(model,connections{k,1},connections{k,2},'autorouting','on');
end
logs = {'DA hold/1','appliedVoltage';'Motor/1','omega';...
    'Motor/2','motorCurrent';'AD hold/1','sampledFeedback'};
for k = 1:size(logs,1)
    name = logs{k,2};
    add_block('simulink/Sinks/To Workspace',[model '/' name],...
        'Position',[810 350+60*k 930 380+60*k],...
        'VariableName',name,'SaveFormat','Timeseries','MaxDataPoints','inf');
    add_line(model,logs{k,1},[name '/1'],'autorouting','on');
end
Simulink.Annotation(model, 'Digital P-controller: Ts also sets sensor latency. velP = [ref, voltage/10, velocity].');
save_system(model,target);
close_system(model,0);
if ~sourceWasLoaded
    close_system(source,0);
end
fprintf('Created %s\n',target);
end
